# mod_code_generation.R
# Module for Reproducible Code Generation
#
# Tracks all user actions in the Shiny app and generates executable R script
# that reproduces the analysis using sapfluxr package functions

# R6 Class for Code Tracking ----
CodeTracker <- R6::R6Class(
  "CodeTracker",
  public = list(
    steps = NULL,
    session_info = NULL,

    initialize = function() {
      self$steps <- list()
      self$session_info <- NULL
    },

    add_step = function(step_name, code, description = NULL, params = list()) {
      step <- list(
        number = length(self$steps) + 1,
        name = step_name,
        code = code,
        description = description,
        params = params,
        timestamp = Sys.time()
      )

      self$steps[[length(self$steps) + 1]] <- step
      invisible(self)
    },

    clear = function() {
      self$steps <- list()
      invisible(self)
    },

    generate_script = function() {
      if (length(self$steps) == 0) {
        return("# No analysis steps recorded yet")
      }

      # Header
      script <- c(
        "# Sap Flow Analysis Script",
        paste("# Generated by sapfluxr Shiny App on", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
        "",
        "# This script reproduces the analysis performed in the Shiny app",
        "# using the sapfluxr package",
        "",
        "# Load required packages",
        "library(sapfluxr)",
        "library(dplyr)",
        "library(ggplot2)",
        "",
        "# Set working directory (update this path)",
        "# setwd(\"/path/to/your/data\")",
        "",
        ""
      )

      # Add each step
      for (i in seq_along(self$steps)) {
        step <- self$steps[[i]]

        # Step header
        script <- c(
          script,
          paste0("# ", rep("=", 70), collapse = ""),
          paste0("# Step ", step$number, ": ", step$name),
          paste0("# ", rep("=", 70), collapse = "")
        )

        # Description if provided
        if (!is.null(step$description) && nchar(step$description) > 0) {
          script <- c(script, paste("#", step$description))
        }

        # Timestamp
        script <- c(script, paste("# Performed:", format(step$timestamp, "%Y-%m-%d %H:%M:%S")))
        script <- c(script, "")

        # Code
        script <- c(script, step$code, "", "")
      }

      # Footer
      script <- c(
        script,
        paste0("# ", rep("=", 70), collapse = ""),
        "# Session Information",
        paste0("# ", rep("=", 70), collapse = ""),
        "# R session info for reproducibility",
        "",
        "sessionInfo()",
        ""
      )

      return(paste(script, collapse = "\n"))
    }
  )
)

# UI ----
codeGenerationUI <- function(id) {
  ns <- NS(id)

  tagList(
    fluidRow(
      # Left column: Controls
      column(
        width = 4,

        # Info box
        box(
          width = 12,
          title = "About Code Generation",
          status = "info",
          solidHeader = TRUE,
          collapsible = TRUE,
          collapsed = FALSE,

          p("This tool generates executable R code that reproduces your entire Shiny analysis workflow."),
          tags$ul(
            tags$li(strong("Purpose:"), " Scientific reproducibility"),
            tags$li(strong("Output:"), " Self-contained R script"),
            tags$li(strong("Usage:"), " Run in R console or RStudio"),
            tags$li(strong("Benefits:"), " Publication-ready, auditable, reusable")
          ),

          hr(),

          h5("Tracked Steps:"),
          verbatimTextOutput(ns("steps_summary")),

          hr(),

          actionButton(
            ns("clear_steps"),
            "Clear All Steps",
            icon = icon("trash"),
            class = "btn-warning",
            style = "width: 100%;"
          )
        ),

        # Export options
        box(
          width = 12,
          title = "Export Options",
          status = "success",
          solidHeader = TRUE,

          conditionalPanel(
            condition = sprintf("output['%s'] == 0", ns("step_count")),
            p(em("No analysis steps recorded yet. Perform analysis in other tabs."))
          ),

          conditionalPanel(
            condition = sprintf("output['%s'] > 0", ns("step_count")),

            checkboxInput(
              ns("include_comments"),
              "Include detailed comments",
              value = TRUE
            ),

            checkboxInput(
              ns("include_sessioninfo"),
              "Include session info",
              value = TRUE
            ),

            checkboxInput(
              ns("include_file_paths"),
              "Include file paths (update before running)",
              value = TRUE
            ),

            hr(),

            downloadButton(
              ns("download_script"),
              "Download R Script",
              class = "btn-success",
              style = "width: 100%; margin-bottom: 10px;"
            ),

            actionButton(
              ns("copy_to_clipboard"),
              "Copy to Clipboard",
              icon = icon("copy"),
              class = "btn-primary",
              style = "width: 100%;"
            )
          )
        )
      ),

      # Right column: Code preview
      column(
        width = 8,

        # Generated code preview
        box(
          width = 12,
          title = "Generated R Script",
          status = "primary",
          solidHeader = TRUE,

          conditionalPanel(
            condition = sprintf("output['%s'] == 0", ns("step_count")),
            p(em("Code will appear here after you perform analysis steps in the app."))
          ),

          conditionalPanel(
            condition = sprintf("output['%s'] > 0", ns("step_count")),

            helpText(
              icon("info-circle"),
              " This script reproduces your analysis. Copy or download to run in R."
            ),

            tags$div(
              style = "background-color: #f5f5f5; border: 1px solid #ddd; border-radius: 4px; padding: 15px; overflow-x: auto;",
              tags$pre(
                style = "margin: 0; white-space: pre-wrap; font-family: 'Courier New', monospace; font-size: 12px;",
                textOutput(ns("generated_code"))
              )
            )
          )
        ),

        # Step-by-step breakdown
        box(
          width = 12,
          title = "Analysis Steps Breakdown",
          status = "info",
          solidHeader = TRUE,
          collapsible = TRUE,
          collapsed = TRUE,

          helpText("Detailed breakdown of each analysis step:"),

          uiOutput(ns("steps_breakdown"))
        )
      )
    )
  )
}

# Server ----
codeGenerationServer <- function(id) {
  moduleServer(id, function(input, output, session) {

    # Initialize code tracker
    tracker <- CodeTracker$new()

    # Step count (for conditional UI)
    output$step_count <- reactive({
      length(tracker$steps)
    })
    outputOptions(output, "step_count", suspendWhenHidden = FALSE)

    # Steps summary
    output$steps_summary <- renderText({
      if (length(tracker$steps) == 0) {
        return("No steps recorded yet.")
      }

      step_names <- sapply(tracker$steps, function(s) s$name)
      paste0(
        length(tracker$steps), " steps recorded:\n\n",
        paste0(seq_along(step_names), ". ", step_names, collapse = "\n")
      )
    })

    # Generated code
    output$generated_code <- renderText({
      tracker$generate_script()
    })

    # Steps breakdown
    output$steps_breakdown <- renderUI({
      if (length(tracker$steps) == 0) {
        return(p(em("No steps recorded.")))
      }

      step_items <- lapply(seq_along(tracker$steps), function(i) {
        step <- tracker$steps[[i]]

        div(
          style = "margin-bottom: 20px; padding: 10px; border: 1px solid #ddd; border-radius: 4px;",
          h5(paste0("Step ", i, ": ", step$name)),
          p(tags$small(
            icon("clock"),
            format(step$timestamp, "%Y-%m-%d %H:%M:%S")
          )),
          if (!is.null(step$description) && nchar(step$description) > 0) {
            p(step$description)
          },
          tags$pre(
            style = "background-color: #f5f5f5; padding: 10px; border-radius: 4px; font-size: 11px;",
            step$code
          )
        )
      })

      tagList(step_items)
    })

    # Clear steps
    observeEvent(input$clear_steps, {
      tracker$clear()
      showNotification("All analysis steps cleared", type = "message")
    })

    # Download script
    output$download_script <- downloadHandler(
      filename = function() {
        paste0("sapfluxr_analysis_", format(Sys.Date(), "%Y%m%d"), ".R")
      },
      content = function(file) {
        writeLines(tracker$generate_script(), file)
      }
    )

    # Copy to clipboard
    observeEvent(input$copy_to_clipboard, {
      script <- tracker$generate_script()

      # Write to temp file and use clip (Windows) or pbcopy (Mac) or xclip (Linux)
      tryCatch({
        if (.Platform$OS.type == "windows") {
          writeLines(script, "clipboard")
        } else if (Sys.info()["sysname"] == "Darwin") {
          tmp <- tempfile()
          writeLines(script, tmp)
          system(paste("cat", tmp, "| pbcopy"))
        } else {
          tmp <- tempfile()
          writeLines(script, tmp)
          system(paste("cat", tmp, "| xclip -selection clipboard"))
        }

        showNotification("Code copied to clipboard!", type = "message", duration = 3)
      }, error = function(e) {
        showNotification(
          "Could not copy to clipboard. Please use download button instead.",
          type = "warning",
          duration = 5
        )
      })
    })

    # Return tracker for other modules to use
    return(list(
      tracker = tracker,
      add_step = function(step_name, code, description = NULL, params = list()) {
        tracker$add_step(step_name, code, description, params)
      }
    ))
  })
}

# Helper function to format parameters for code
format_params <- function(params) {
  if (length(params) == 0) return("")

  param_strings <- sapply(names(params), function(name) {
    value <- params[[name]]
    if (is.character(value)) {
      paste0(name, ' = "', value, '"')
    } else if (is.logical(value)) {
      paste0(name, " = ", toupper(as.character(value)))
    } else if (is.null(value)) {
      paste0(name, " = NULL")
    } else {
      paste0(name, " = ", value)
    }
  })

  paste(param_strings, collapse = ",\n  ")
}
